### ISSUE TITLE
Library cannot read file, that exiftool reads properly

### ISSUE THREAD

**Issue by qarmin** [mindeng/nom-exif#2]
```
        let file_reader = std::fs::File::open(i.path()).unwrap();
        match nom_exif::parse_jpeg_exif(file_reader) {
            Ok(_) => {
                println!("{}: OK", path_str);
            }
            Err(e) => {
                println!("{}: {}", path_str, e);
            }
        }
```
shows error
```
/home/rafal/Downloads/Untitled Folder/301581895-a7b4390a-e9f4-46cc-b04f-eb1ba677204c.jpg: parse failed; error: Map on Result; 
```

problematic file

[301581895-a7b4390a-e9f4-46cc-b04f-eb1ba677204c.jpg.zip](https://github.com/TechnikTobi/little_exif/files/14141942/301581895-a7b4390a-e9f4-46cc-b04f-eb1ba677204c.jpg.zip)

exiftool only warning - properly parse entire file
```
[minor] Skipped unknown 7 bytes after JPEG APP1 segment
```

**Comment by qarmin** [comment]
Is it possible to ignore the errors and return the exif data that was extracted correctly?

**Comment by mindeng** [comment]
Sorry for replying so late, I will reopen this issue and try to improve it. Thank you for your feedback!

**Comment by mindeng** [comment]
This problem has been completely solved! 

The reason for this problem is that when parsing `IFD`, as long as one of the `DirectoryEntry` fails to parse, it will stop parsing and report an error. The new implementation will ignore the errors encountered during parsing of `DirectoryEntry`, and continue trying to parse subsequent data.

If you are interested in the implementation details, you can refer to [this commit](https://github.com/mindeng/nom-exif/commit/069eb074ac312a2da00c807debf28bb3ac90baa9).

If you encounter other problems, please feel free to submit a bug, thank you!
