### ISSUE TITLE
Unsupported mov file?

### ISSUE THREAD

**Issue by wsyxbcl** [mindeng/nom-exif#7]
Here are a sample files, hope it's helpful. 
[Google drive](https://drive.google.com/file/d/18U9QnHNXPwQAvTqJRS4hR90aFHPHNhAs) is used due to github file size limit.

There are also some mp4 files that can not be recognized, will provide you example later if you're interested.

**Comment by mindeng** [comment]
Thank you so much! I will check and fix the problem as soon as possible! 

If it is convenient, please help provide other mp4 files that cannot be parsed, thank you!

**Comment by mindeng** [comment]
This issue has been fixed. The reason for the issue was that in the previous implementation, when the `moov` box was not found, it was treated as an error and stopped parsing subsequent metadata. The current implementation ignores this problem and continues to parse subsequent metadata.

If interested, you can refer to this [commit](https://github.com/mindeng/nom-exif/commit/795648687c175e3185622677063cbb7a05b1f334). 

You can try the new version and see if there are any problems with other videos. Thanks again for your feedback!

**Comment by wsyxbcl** [comment]
Thanks for the quick fix and detailed explanation.

> If it is convenient, please help provide other mp4 files that cannot be parsed. 

I currently only have media from a few camera models, and I'll test data from more camera models next week. Here's one of those files for you to try. [Google drive link](https://drive.google.com/file/d/1-lgQMqZV1ki5bAyMbkr6VKhYGPYMVYki/view?usp=sharing)

Thank you for being interested.

**Comment by mindeng** [comment]
I did a test using the file you uploaded later, and I did find a new problem. When calculating `duration`, due to the large `time_sacle` of the file, the multiplication overflowed, thus reporting a parsing failure.

The new implementation fixes this problem and uses the `f64` type for `duration`calculations, which will no longer cause overflow.

If you find other issues,please feel free to file a bug, thank you!
